### ISSUE TITLE
Wrong position of the daterange-picker

### ISSUE THREAD

**Issue by valneras** [ashishgkwd/ngx-mat-daterange-picker#1]
Hello,
I've got a bug with the  position of the daterange-picker if the field is locatated at the bottom of the page : 
![datepickerposition](https://user-images.githubusercontent.com/3040636/40069473-bf90fe94-586b-11e8-8dc6-7a0e2a24d698.png) Date picker is cropped.
Is there an option to manage the position of the datepicker or is it another problem?

Thanks for your work on this component.

**Comment by ashishgkwd** [comment]
@valneras work is in progress to add the Material [`flexibleConnectedPositionStrategy`](https://material.angular.io/cdk/overlay/api#FlexibleConnectedPositionStrategy), as well as make the component mobile friendly.
Thank you for raising this. I should be able to release a patch version with this fix in a day or two.
Meanwhile, can you please share the version number you are using.

**Comment by valneras** [comment]
Hi, the version number is v1.0.0 with Angular 6.0.
Thanks for your support!

**Comment by ashishgkwd** [comment]
@valneras have released a minor version 1.1.0 with the position strategy fix and some additional (optional) configuration for the datepicker overlay.

You can verify the fix by upgrading to v1.1.0 or changing the class `.demo-main` at the [demo](https://ashishgkwd.github.io/ngx-mat-daterange-picker/) page to play around various positions.

Will close the issue once I hear back from you. 
Cheers.

**Comment by ashishgkwd** [comment]
Closing the issue post verification.
