### ISSUE TITLE
Angular 6 update

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [ashishgkwd/ngx-mat-daterange-picker#10]
Hi

Please update the Angular packages:

![image](https://user-images.githubusercontent.com/30147726/45401969-897cd300-b653-11e8-8c72-71e3d5425cca.png)

And the datepicker unfortunately not responsive.

**Comment by ashishgkwd** [comment]
@reva2 PR #12 enables support for Angular 6.1
Will open a separate issue for responsiveness.
