### ISSUE TITLE
selectedDateRangeChanged is triggered on cancel

### ISSUE THREAD

**Issue by volodymyro-in6k** [ashishgkwd/ngx-mat-daterange-picker#11]
Hi, thanks for your lib. It's really great!

selectedDateRangeChanged is triggered on cancel. Not sure that it's expected behavior.

**Comment by ashishgkwd** [comment]
You are right and thanks for the good catch 👍 
There is no reason for the component to trigger `selectedDateRangeChanged` on cancel.
Fixed in release v1.1.4

Verified at https://multi-ngx-mat-daterange-picker-example.stackblitz.io
